// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baxcdvbfopxucxnakxrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJheGNkdmJmb3B4dWN4bmFreHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjQ4MTAsImV4cCI6MjA2ODI0MDgxMH0.D5tyhvKFdgenXEXzACU0KtV_bmrYPUDBu6k-kVlmuCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});